const CENTER=[50.5309,15.3734];
let radiusKm=5;
const map=L.map('map').setView(CENTER,13);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);
const radiusCircle=L.circle(CENTER,{radius:5000,weight:2,dashArray:'6 6',fillOpacity:.035}).addTo(map);
const layer=L.layerGroup().addTo(map); let firms=[];
const $=id=>document.getElementById(id);
const dist=(a,b)=>{const R=6371000,p=Math.PI/180,dLat=(b[0]-a[0])*p,dLon=(b[1]-a[1])*p,x=Math.sin(dLat/2)**2+Math.cos(a[0]*p)*Math.cos(b[0]*p)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(x));};
const sectorColors={'Zemědělství, lesnictví a rybářství':'#2e7d32','Těžba a dobývání':'#795548','Zpracovatelský průmysl':'#1565c0','Energetika a zásobování energiemi':'#f9a825','Voda, odpady a sanace':'#00838f','Stavebnictví':'#ef6c00','Obchod a opravy motorových vozidel':'#8e24aa','Velkoobchod a maloobchod':'#6a1b9a','Doprava a skladování':'#3949ab','Ubytování a stravování':'#d81b60','Informace a komunikace':'#00897b','Finance a pojišťovnictví':'#546e7a','Nemovitosti':'#5d4037','Profesní, vědecké a technické činnosti':'#00acc1','Administrativní a podpůrné činnosti':'#7cb342','Veřejná správa a obrana':'#424242','Vzdělávání':'#1e88e5','Zdravotní a sociální péče':'#c62828','Kultura, zábava a rekreace':'#ad1457','Ostatní služby':'#6d4c41','Domácnosti jako zaměstnavatelé':'#757575','Domácnosti jako výrobci':'#757575','Exteritoriální organizace':'#212121','Ostatní / nezařazené':'#9e9e9e'};
const sizeRadius={'Neuvedeno':5,'Bez zaměstnanců':5,'1–5 zaměstnanců':6,'6–9 zaměstnanců':7,'10–19 zaměstnanců':8,'20–24 zaměstnanci':9,'25–49 zaměstnanců':10,'50–99 zaměstnanců':12,'100–199 zaměstnanců':15,'200–249 zaměstnanců':17,'250–499 zaměstnanců':20,'500–999 zaměstnanců':23,'1 000–1 499 zaměstnanců':26,'1 500–1 999 zaměstnanců':29,'2 000–2 499 zaměstnanců':32,'2 500–2 999 zaměstnanců':35,'3 000–3 999 zaměstnanců':38,'4 000–4 999 zaměstnanců':41,'5 000–9 999 zaměstnanců':44,'10 000+ zaměstnanců':48};
function options(id,values){const s=$(id),old=s.value; [...new Set(values.filter(Boolean))].sort((a,b)=>a.localeCompare(b,'cs')).forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;s.appendChild(o)});s.value=old}
function marker(f){const color=sectorColors[f.sector]||'#9e9e9e',size=sizeRadius[f.size]||6;const m=L.circleMarker([f.lat,f.lon],{radius:size,color,weight:1,fillColor:color,fillOpacity:.78});m.bindPopup(`<div class="popup"><h3>${esc(f.name)}</h3>${f.ico?`<p><b>IČO:</b> ${esc(f.ico)}</p>`:''}<p><b>Adresa:</b> ${esc(f.address||'neuvedena')}</p><p><b>Obor:</b> ${esc(f.sector||'neuveden')}</p>${f.nace?`<p><b>CZ-NACE 2025:</b> ${esc(f.nace)}</p>`:''}<p><b>Velikost:</b> ${esc(f.size||'neuvedena')}</p><p><b>Právní forma:</b> ${esc(f.legal||'neuvedena')}</p>${f.workers_note?`<p class="muted">${esc(f.workers_note)}</p>`:''}</div>`);return m}
function esc(v){return String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}
function render(){layer.clearLayers();const q=$('search').value.trim().toLowerCase(),sec=$('sector').value,sz=$('size').value,leg=$('legal').value,dr=$('distance').value;let shown=0;firms.forEach(f=>{const d=dist(CENTER,[f.lat,f.lon]),km=d/1000;let ok=d<=radiusKm*1000&&(!q||`${f.name} ${f.ico} ${f.address}`.toLowerCase().includes(q))&&(!sec||f.sector===sec)&&(!sz||f.size===sz)&&(!leg||f.legal===leg);if(dr){const [a,b]=dr.split('-').map(Number);ok=ok&&km>=a&&km<=b}if(ok){marker(f).addTo(layer);shown++}});$('visible').textContent=shown;$('count').textContent=`${shown} subjektů`}
$('radius').addEventListener('change',()=>{radiusKm=Number($('radius').value);radiusCircle.setRadius(radiusKm*1000);map.fitBounds(radiusCircle.getBounds(),{padding:[20,20]});render()});
['search','sector','size','legal','distance'].forEach(id=>$(id).addEventListener('input',render));
fetch('data/firms.json').then(r=>r.json()).then(data=>{firms=data.filter(f=>Number.isFinite(f.lat)&&Number.isFinite(f.lon));options('sector',firms.map(f=>f.sector));options('size',firms.map(f=>f.size));options('legal',firms.map(f=>f.legal));render()}).catch(()=>{$('count').textContent='Chyba načtení dat'});
